package io.github.dsheirer.source.tuner.sdrplay.api;

import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sdrplay_api_ErrorInfoT extends Structure {
	/** C type : char[256] */
	public byte[] file = new byte[256];
	/** C type : char[256] */
	public byte[] function = new byte[256];
	public int line;
	/** C type : char[1024] */
	public byte[] message = new byte[1024];
	public sdrplay_api_ErrorInfoT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("file", "function", "line", "message");
	}
	/**
	 * @param file C type : char[256]<br>
	 * @param function C type : char[256]<br>
	 * @param message C type : char[1024]
	 */
	public sdrplay_api_ErrorInfoT(byte file[], byte function[], int line, byte message[]) {
		super();
		if ((file.length != this.file.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.file = file;
		if ((function.length != this.function.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.function = function;
		this.line = line;
		if ((message.length != this.message.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.message = message;
	}
	public static class ByReference extends sdrplay_api_ErrorInfoT implements Structure.ByReference {
		
	};
	public static class ByValue extends sdrplay_api_ErrorInfoT implements Structure.ByValue {
		
	};
}
